#page title
page_title: Weaved

# App Info
ios_app_id: 1234793120
ios_app_country: us

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Weaved
app_price: Helping men to dress better.
app_description: Coming soon to Public Beta

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name:
your_link:
your_city:
email_address:
facebook_username:
instagram_username: weaved.app
twitter_username: weavedapp
github_username: jsh8w
youtube_username:
mastodon_link:

# Feature List
features:
  - title: Helping Men dress better
    description: Our mission is to help men dress effortlessly stylishly.
    fontawesome_icon_name: magic

  - title: Personalised Recommendations
    description: Style your wardrobe with personalised outfit recommendations.
    fontawesome_icon_name: tshirt

  - title: Outfit Ideas
    description: Weaved keeps tabs on the latest styles to keep your wardrobe up to date.
    fontawesome_icon_name: socks

  - title: Powerful Algorithms
    description: Our powerful AI recommendations engine learns your style and body.
    fontawesome_icon_name: user

  - title: Browse & Filter
    description: Browse through hundreds of products personalised to your style.
    fontawesome_icon_name: filter

  - title: Fashion Tips & Likes
    description: Track your favourite pieces for a day in the office or an evening out.
    fontawesome_icon_name: star

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.65

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
